name: Continuous deployment
on:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable WASM
        run: rustup target add wasm32-unknown-unknown

      - name: Install trunk
        run: cargo install trunk

      - run: trunk build --release --public-url /${{ github.event.repository.name }}/

      - uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist